### ISSUE TITLE
Plan to port Pulsar2d to Linux or Haiku

### ISSUE THREAD

**Issue by lorglas** [MarkusMangold/Pulsar2d#1]
Is there a plan to port Pulsar 2D to Linux or Haiku and by the way EGSL run under 32Bit and 64Bit Haiku.

**Comment by MarkusMangold** [comment]
Pulsar2d will be released as open source. So on any operating system supporting FreeBASIC or Freepascal, SDL2, SDL2_image and SLD2_mixer you can also use Pulsar2d.

**Comment by lorglas** [comment]
> Pulsar2d will be released as open source. So on any operating system supporting FreeBASIC or Freepascal, SDL2, SDL2_image and SLD2_mixer you can also use Pulsar2d. 

Ok, i will waiting to the released of Pulsar2d and o hope i can generate a working Version for haiku. 

On the egsl.retrobasic.org Webseite the Downloads doesn't works. It is possible to get the source for bubblechain (egsl). 

And one questions more. The license of all examples from egsl are under zlib? 

Can we change (original copyright owner stays in the history)and distribute the software. I think in the past lelldorin has ask and we get a yes. 
Regards 
BeSly Team

**Comment by MarkusMangold** [comment]
Pulsar2d is not a Lua interpreter. It's just a framework to use with Freepascal and FreeBASIC. Since FreeBASIC doesn't work on Haiku, I think you'll have to use Freepascal. 
Most examples of EGSL are released under the zlib license. However, this is not the case with Bubblechain and Astrorocks which were both released as closed source games.
The website for EGSL was cancelled a long time ago. I don't know why it's still online.

**Comment by lorglas** [comment]
Can we generate a package for Bubblechain and Astrorocks (both egsl version). So there  are great games and it would be a shame if they just disappeared. 
In the package we can wrote that the License is closed source, we don't change on the source code anything. i hope you say yes.

**Comment by lorglas** [comment]
i found a old mail between Christian and you , in that you allow to put the source in the from Astrorocks (old Variant from EGSL time) in the HAIKU IDE. And BubbleChain, we can host only a Package which can be downloaded. Nothing was changed.

**Comment by MarkusMangold** [comment]
I cannot reactivate the website, the contract was terminated a long time ago. -the second point is that EGSL is not developed anymore and abandoned years ago. I only develop Pulsar2d, so this is this github repository for.

**Comment by lorglas** [comment]
I'm only annoying because we want to make sure that we don't violate any rights.  If there are no objections, I see no problem that we host the packages.  Then we can close the issue.
